airline/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/', include('flights.urls')),
    path('user/', include('user.urls'))
]

flights/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book")
]

user/urls.py
from django.urls import path
from . import views

app_name = "u"
urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
]

flights/models.py
from django.db import models

# Create your models here.


class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"


class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"

    def is_valid_flight(self):
        return self.origin != self.destination and self.duration >= 0


class Passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self):
        return f"{self.first} {self.last}"

user/models.py
from django.db import models

# Create your models here.

flights/views.py
from django.shortcuts import render
from .models import Flight, Airport, Passenger
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse

# Create your views here.


def index(request):
    return render(request, 'flights/index.html', {
        "flights": Flight.objects.all()
    })


def flight(request, flight_id):
    try:
        f = Flight.objects.get(id=flight_id)
    except Flight.DoesNotExist:
        raise Http404("Flight not found!")
    p = f.passengers.all()
    non_p = Passenger.objects.exclude(flights=f).all()
    return render(request, 'flights/flight.html', {
        "flight": f,
        "passengers": p,
        "non_passenger": non_p
    })


def book(request, flight_id):
    if request.method == "POST":
        flight = Flight.objects.get(pk=flight_id)
        passenger_id = int(request.POST['passenger'])
        passenger = Passenger.objects.get(pk=passenger_id)
        passenger.flights.add(flight)
        return HttpResponseRedirect(reverse('flight', args=(flight.id,)))

user/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

# Create your views here.


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('u:login'))
    return render(request, 'users/user.html')


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse("u:index"))
        else:
            return render(request, 'users/login.html', {
                "message": "Invalid Credentials"
            })
    return render(request, 'users/login.html')


def logout_view(request):
    logout(request)
    return render(request, 'users/login.html', {
        "message": "Logged out"
    })

flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flight {{ f.id }}</h1>
    <ul>
        <li>Origin: {{ flight.origin }}</li>
        <li>Destination: {{ flight.destination }}</li>
        <li>Duration: {{ flight.duration }}</li>
    </ul>
    <a href="{% url 'index' %}">All flights</a>

    <h2>Passengers:</h2>
    {% for passenger in passengers %}
        <li>{{ passenger }}</li>
        {% empty %}
        <li style="color: gray"><em>No Passengers</em></li>
    {% endfor %}

    <h2>Add passenger:</h2>
    <form action="{% url 'book' flight.id %}" method="post">
        {% csrf_token %}
        <select name="passenger" id="">
            {% for passenger in non_passenger %}
                <option value="{{ passenger.id }}">{{ passenger }}</option>
            {% endfor %}
        </select>
        <input type="submit">
    </form>
{% endblock %}

flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
    <h1>Flights:</h1>
    <ul>
        {% for flights in flights %}
            <li>
                <a href="{% url 'flight' flights.id %}">
                {{ flights.id }}: &nbsp;{{ flights.origin }} to {{ flights.destination }} in {{ flights.duration }} minutes
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

flights/templates/flights/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Flights</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

user/templates/users/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Users</title>
</head>
<body>
    {% block body %}

    {% endblock %}
</body>
</html>

user/templates/users/login.html
{% extends 'users/layout.html' %}

{% block body %}
    {{ message }}
    <form action="{% url 'u:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value="login">
    </form>
{% endblock %}

user/templates/users/user.html
{% extends 'users/layout.html' %}

{% block body %}
    <h1>Welcome, {{ request.user.first_name }}</h1>
    <ul>
        <li>Username: {{ request.user.username }}</li>
        <li>Email: {{ request.user.email }}</li>
    </ul>

    <a href="{% url 'u:logout' %}">Logout</a>
{% endblock %}